spring.application.name=Obras

spring.datasource.url=jdbc:postgresql://localhost:5432/construgestor
spring.datasource.username=postgres
spring.datasource.password=12879923
spring.datasource.driver-class-name=org.postgresql.Driver

spring.web.resources.static-locations=file:uploads/,classpath:/static/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=o8FY8KAZ28msLVD70xyPy2Xn93v5bpBcNg9PosQhfCT
jwt.expiration=86400000