spring.application.name=Obras

spring.datasource.url=jdbc:h2:mem:construgestor
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.datasource.url=jdbc:postgresql://localhost:5432/construgestor
spring.datasource.username=postgres
spring.datasource.password=12879923
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true